SDU_DATA = [
    "Cookie Without HttpOnly Flag Detected",
    "Cookie Without Secure Flag Detected",
    "Missing 'Cache-Control' Header",
    "Cookie Without SameSite Flag Detected",
    "Missing Content Security Policy",
    "HTTP to HTTPS Redirect Not Enabled",
    "Permissive Content Security Policy Detected",
    "Cross-site Scripting (XSS)",
    "Cross-Site Scripting (XSS) in HTML tag",
    "Missing 'X-Content-Type-Options' Header",
    "Login Form Cross-Site Request Forgery",
    "Missing HTTP Strict Transport Security Policy",
    "Missing 'X-Frame-Options' Header",
    "jQuery 1.2.0 < 3.5.0 Cross-Site Scripting",
    "jQuery UI < 1.13.2 Cross-Site Scripting",
    "jQuery UI < 1.13.0 Multiple Vulnerabilities",
    "Insecure 'Access-Control-Allow-Origin' Header",
    "jQuery < 3.4.0 Prototype Pollution",
    "jQuery 1.4.2 < 1.6.2 Cross-Site Scripting",
    "jQuery UI < 1.10.0 Multiple Vulnerabilities",
    "jQuery UI < 1.12.0 Cross-Site Scripting",
    "jQuery 1.4.0 < 1.12.0 Cross-Site Scripting",
    "jQuery < 1.6.3 Cross-Site Scripting",
    "Gitignore File Detected",
    "Drupal 8.7.x < 9.5.11 Cache Poisoning",
    "Drupal Unsupported Version",
    "Host Header Injection",
    "Web Cache Poisoning",
    "Password Field With Auto-Complete",
    "HTTP Header Information Disclosure",
    "Missing 'Content-Type' Header",
    "Moment.js < 2.15.2 Regular Expression Denial of Service",
    "Bootstrap < 3.4.0 Cross-Site Scripting",
    "Bootstrap 3.x < 3.4.1 Cross-Site Scripting",
    "jQuery 1.7.1 < 1.9.0 Cross-Site Scripting",
    "jQuery 1.12.4 < 3.0.0 Cross-Site Scripting",
    "Moment.js < 2.19.3 Regular Expression Denial of Service",
    "HTML/CSS Injection",
    "Package Dependencies Detected",
    "Moment.js 2.18.x < 2.29.4 Regular Expression Denial of Service",
    "SSL/TLS Forward Secrecy Cipher Suites Not Supported",
    "SSL/TLS Weak Cipher Suites Supported",
    "Password Submitted using get Method",
    "External Broken Resources Detected",
    "Polyfill Detected",
    "jQuery < 1.9.0 Cross-Site Scripting",
    "Lodash < 4.17.21 Multiple Vulnerabilities",
    "Lodash < 4.17.20 Prototype Pollution",
    "Lodash < 4.17.12 Prototype Pollution",
    "HandlebarsJS < 4.3.0 Prototype Pollution",
    "HandlebarsJS < 4.7.7 Multiple Vulnerabilities",
    "HandlebarsJS < 3.0.8 Arbitrary Code Execution",
    "Secret Data Disclosure",
    "Drupal 10.2.x < 10.2.11 Multiple Vulnerabilities",
    "Mixed Resource Detection",
    "Content Security Policy Missing 'Report-To'"
]
