SAST_DATA = [
    "AngularJS Misconfiguration: Strict Contextual Escaping Disabled",
    "Build Misconfiguration: External Maven Dependency Repository",
    "Code Correctness: Double-Checked Locking",
    "Code Correctness: Erroneous Class Compare",
    "Code Correctness: Erroneous Null Comparison",
    "Code Correctness: Hidden Method",
    "Code Correctness: String Comparison of Float",
    "Cookie Security: Cookie not Sent Over SSL",
    "Cookie Security: Persistent Cookie",
    "Cross-Site Scripting: Poor Validation",
    "Dangerous File Inclusion",
    "Dead Code: Expression is Always false",
    "Dead Code: Expression is Always true",
    "Denial of Service: Parse Double",
    "Dynamic Code Evaluation: Code Injection",
    "EJB Bad Practices: Use of AWT/Swing",
    "EJB Bad Practices: Use of Sockets",
    "Hardcoded Domain in HTML",
    "HTML5: Form Validation Turned Off",
    "J2EE Bad Practices: getConnection()",
    "LDAP Injection",
    "Obsolete",
    "Often Misused: Authentication",
    "OGNL Expression Injection: Struts 2",
    "Process Control",
    "Race Condition: Class Initialization Cycle",
    "Race Condition: Static Database Connection",
    "Setting Manipulation",
    "SQL Injection",
    "Struts 2 Bad Practices: Dynamic Method Invocation",
    "Struts 2: Unvalidated Action",
    "Struts: Unused Action Form",
    "Unreleased Resource: Sockets",
    "Unsafe JNI",
    "Unsafe Mobile Code: Inner Class",
    "WebSphere Service Provider Misconfiguration: Inbound WS-Security Not Enabled",
    "WebSphere Service Requester Misconfiguration: Missing Outbound Timestamp",
    "Access Control: SecurityManager Bypass",
    "Code Correctness: Call to Thread.stop()",
    "Code Correctness: Class Does Not Implement Cloneable",
    "Code Correctness: Class Does Not Implement equals",
    "Code Correctness: Erroneous finalize() Method",
    "Code Correctness: null Argument to equals()",
    "Cross-Site Request Forgery",
    "Cross-Site Scripting: Reflected",
    "Dynamic Code Evaluation: JNDI Reference Injection",
    "EJB Bad Practices: Use of java.io",
    "File Disclosure: Struts",
    "Header Manipulation",
    "Header Manipulation: Cookies",
    "HTML5: Overly Permissive Message Posting Policy",
    "HTTP Verb Tampering",
    "J2EE Misconfiguration: Excessive Servlet Mappings",
    "J2EE Misconfiguration: Missing Filter Definition",
    "JSON Injection",
    "Key Management: Null Encryption Key",
    "Log Forging",
    "Missing XML Validation",
    "Object Model Violation: Just one of equals() and hashCode() Defined",
    "Password Management",
    "Password Management: Empty Password",
    "Poor Error Handling: Overly Broad Catch",
    "Poor Error Handling: Program Catches NullPointerException",
    "Poor Error Handling: Throw Inside Finally",
    "Poor Logging Practice: Logger Not Declared Static Final",
    "Poor Logging Practice: Use of a System Output Stream",
    "Privacy Violation",
    "Race Condition: Singleton Member Field",
    "Server-Side Request Forgery",
    "System Information Leak: Internal",
    "Unreleased Resource: Files",
    "Weak Cryptographic Hash",
    "Weak Encryption: Insecure Initialization Vector",
    "XML Entity Expansion Injection",
    "Access Control: Database",
    "Access Control: Weak Security Constraint",
    "Code Correctness: Multiple Stream Commits",
    "Code Correctness: Non-Static Inner Class Implements Serializable",
    "Cookie Security: Overly Broad Path",
    "Dynamic Code Evaluation: Unsafe Deserialization",
    "File Disclosure: J2EE",
    "Header Manipulation: SMTP",
    "HTML5: MIME Sniffing",
    "HTML5: Missing Content Security Policy",
    "HTML5: Overly Permissive CORS Policy",
    "J2EE Bad Practices: Leftover Debug Code",
    "J2EE Bad Practices: Sockets",
    "J2EE Bad Practices: Threads",
    "J2EE Misconfiguration: Duplicate Servlet Mapping",
    "J2EE Misconfiguration: Excessive Session Timeout",
    "J2EE Misconfiguration: Insecure Transport",
    "JavaScript Hijacking: Vulnerable Framework",
    "LDAP Manipulation",
    "Missing Check for Null Parameter",
    "Password Management: Password in HTML Form",
    "Path Manipulation",
    "Path Manipulation: Zip Entry Overwrite",
    "Poor Error Handling: Empty Catch Block",
    "Poor Error Handling: Return Inside Finally",
    "Privacy Violation: Autocomplete",
    "Struts: Form Does Not Extend Validation Class",
    "Struts: Plugin Framework Not In Use",
    "Struts: Unused Validation Form",
    "Struts: Unvalidated Action Form",
    "Struts: Validator Without Form Field",
    "System Information Leak: Incomplete Servlet Error Handling",
    "Unsafe Mobile Code: Unsafe Public Field",
    "Weak XML Schema: Type Any",
    "Weak XML Schema: Undefined Namespace",
    "WebSphere Service Provider Misconfiguration: Missing Inbound Signature",
    "WebSphere Service Provider Misconfiguration: Missing Inbound Timestamp",
    "Axis 2 Service Provider Misconfiguration: WS-Security Not Enabled",
    "Code Correctness: Byte Array to String Conversion",
    "Code Correctness: Constructor Invokes Overridable Function",
    "Code Correctness: Incorrect Serializable Method Signature",
    "Code Correctness: Non-Synchronized Method Overrides Synchronized Method",
    "Command Injection",
    "Cookie Security: HTTPOnly not Set",
    "Cross-Site Scripting: Self",
    "Dead Code: Unused Field",
    "Dynamic Code Evaluation: XMLDecoder Injection",
    "Formula Injection",
    "Insecure SSL: Overly Broad Certificate Trust",
    "J2EE Bad Practices: Non-Serializable Object Stored in Session",
    "J2EE Misconfiguration: Missing Security Role",
    "JavaScript Hijacking",
    "OGNL Expression Injection: Double Evaluation",
    "OGNL Expression Injection: Dynamic Method Invocation",
    "Poor Error Handling: Overly Broad Throws",
    "Poor Style: Identifier Contains Dollar Symbol ($)",
    "Poor Style: Non-final Public Static Field",
    "Portability Flaw: Locale Dependent Comparison",
    "Privilege Management: Default Package Rights",
    "Struts 2: Validation File Without Action",
    "Struts Misconfiguration: Duplicate Form Bean",
    "Struts Misconfiguration: Missing Action Input",
    "Struts: Erroneous validate() Method",
    "Struts: Form Field Without Validator",
    "System Information Leak: External",
    "Trust Boundary Violation",
    "Unchecked Return Value",
    "Unreleased Resource: Streams",
    "WCF Misconfiguration: Insufficient Logging",
    "WCF Misconfiguration: Throttling Not Enabled",
    "Weak Cryptographic Hash: Insecure PBE Iteration Count",
    "WebSphere Misconfiguration: Servlets Served By Class Name",
    "WebSphere Service Provider Misconfiguration: Missing Inbound Encryption",
    "WebSphere Service Requester Misconfiguration: Outbound WS-Security Not Enabled",
    "XML External Entity Injection",
    "Access Control: LDAP",
    "Access Specifier Manipulation",
    "ClassLoader Manipulation: Struts 1",
    "Code Correctness: clone() Invokes Overridable Function",
    "Code Correctness: Comparison of Boxed Primitive Types",
    "Code Correctness: Invalid Call to Object.equals()",
    "Code Correctness: toString on Array",
    "Cross-Site Scripting: DOM",
    "Dead Code: Empty Try Block",
    "Denial of Service",
    "Denial of Service: Regular Expression",
    "Denial of Service: StringBuilder",
    "Dynamic Code Evaluation: Script Injection",
    "EJB Bad Practices: Use of Class Loader",
    "Hidden Field",
    "Insecure Randomness",
    "Insecure Transport",
    "J2EE Bad Practices: JVM Termination",
    "J2EE Misconfiguration: Incomplete Error Handling",
    "J2EE Misconfiguration: Missing Data Transport Constraint",
    "Key Management: Empty Encryption Key",
    "Key Management: Hardcoded Encryption Key",
    "Mass Assignment: Sensitive Field Exposure",
    "Missing Check against Null",
    "OGNL Expression Injection: Double Evaluation",
    "Password Management: Insecure Submission",
    "Poor Style: Confusing Naming",
    "Poor Style: Redundant Initialization",
    "Portability Flaw: File Separator",
    "Privilege Management: Overly Broad Grant",
    "Race Condition",
    "Session Fixation",
    "Struts Misconfiguration: Invalid Path",
    "Struts: Validator Turned Off",
    "System Information Leak: HTML Comment in JSP",
    "Unreleased Resource: Database",
    "Weak Encryption: Insecure Mode of Operation",
    "WebSphere Service Provider Misconfiguration: Missing Outbound Encryption",
    "WebSphere Service Requester Misconfiguration: Missing Inbound Encryption",
    "WebSphere Service Requester Misconfiguration: Missing Inbound Timestamp",
    "WebSphere Service Requester Misconfiguration: Missing Outbound Encryption",
    "ASP.NET Misconfiguration: Debug Information",
    "Client-Side Template Injection",
    "Cross-Site Scripting: Persistent",
    "Dead Code: Unused Method",
    "Denial of Service: Format String",
    "EJB Bad Practices: Use of Synchronization Primitives",
    "Insecure Transport: Mail Transmission",
    "J2EE Misconfiguration: Missing Authentication Method",
    "J2EE Misconfiguration: Missing Error Handling",
    "Log Forging (debug)",
    "Null Dereference",
    "Object Model Violation: Erroneous clone() Method",
    "Often Misused: File Upload",
    "Open Redirect",
    "Password Management: Empty Password in Configuration File",
    "Password Management: Hardcoded Password",
    "Password Management: Null Password",
    "Password Management: Password in Comment",
    "Password Management: Password in Configuration File",
    "Poor Style: Value Never Read",
    "Privacy Violation: Heap Inspection",
    "Privilege Management: Default Function or Procedure Rights",
    "Privilege Management: Overly Broad Access Specifier",
    "Race Condition: Format Flaw",
    "Redundant Null Check",
    "Resource Injection",
    "Spring Security Misconfiguration: Incorrect Request Matcher Type",
    "Struts Misconfiguration: Missing Form Bean",
    "System Information Leak",
    "Unsafe Reflection",
    "WCF Misconfiguration: Service Enumeration",
    "Weak Cryptographic Hash: Missing Required Step",
    "Weak Encryption",
    "Weak XML Schema: Lax Processing",
    "Weak XML Schema: Unbounded Occurrences",
    "WebSphere Service Provider Misconfiguration: Missing Outbound Signature",
    "WebSphere Service Provider Misconfiguration: Missing Outbound Timestamp",
    "WebSphere Service Provider Misconfiguration: Outbound WS-Security Not Enabled",
    "WebSphere Service Requester Misconfiguration: Inbound WS-Security Not Enabled",
    "XSLT Injection",
    "Insecure Transport: Disabled App Transport Security",
    "Poor Logging Practice: Multiple Loggers",
    "System Information Leak: Overly Broad SQL Logging",
    "Code Correctness: Call to System.gc()",
    "Privacy Violation: Shoulder Surfing",
    "Struts: Duplicate Validation Forms",
    "XPath Injection",
    "Code Correctness: Incorrect serialPersistentFields Modifier",
    "Insecure Randomness: Hardcoded Seed",
    "Weak Encryption: Inadequate RSA Padding",
    "Struts Misconfiguration: Missing Form Property Type",
    "Weak Encryption: Insufficient Key Size",
    "Code Correctness: readObject() Invokes Overridable Function",
    "J2EE Misconfiguration: Missing Servlet Mapping",
    "Often Misused: Boolean.getBoolean()",
    "Access Control: SecurityManager Bypass",
    "Client-Side Template Injection",
    "Code Correctness: Call to Thread.stop()",
    "Code Correctness: Constructor Invokes Overridable Function",
    "Code Correctness: Double-Checked Locking",
    "Code Correctness: Erroneous Class Compare",
    "Cookie Security: HTTPOnly not Set on Application Cookie",
    "Cross-Site Request Forgery",
    "Cross-Site Scripting: Persistent",
    "Denial of Service: Parse Double",
    "File Disclosure: J2EE",
    "Header Manipulation",
    "HTML5: Form Validation Turned Off",
    "HTML5: Missing Content Security Policy",
    "J2EE Bad Practices: getConnection()",
    "J2EE Bad Practices: JVM Termination",
    "J2EE Bad Practices: Non-Serializable Object Stored in Session",
    "J2EE Misconfiguration: Excessive Session Timeout",
    "Key Management: Null Encryption Key",
    "Log Forging",
    "Obsolete",
    "Password Management: Empty Password in Configuration File",
    "Password Management: Empty Password",
    "Poor Logging Practice: Logger Not Declared Static Final",
    "Poor Logging Practice: Use of a System Output Stream",
    "Portability Flaw: Locale Dependent Comparison",
    "Privacy Violation: Shoulder Surfing",
    "Race Condition",
    "Struts Misconfiguration: Missing Action Input",
    "Struts Misconfiguration: Missing Form Bean",
    "Struts: Unvalidated Action Form",
    "WCF Misconfiguration: Insufficient Logging",
    "WCF Misconfiguration: Service Enumeration",
    "Weak Cryptographic Hash: Insecure PBE Iteration Count",
    "Weak Cryptographic Hash: Missing Required Step",
    "Weak Encryption: Insecure Mode of Operation",
    "Weak XML Schema: Undefined Namespace",
    "WebSphere Service Provider Misconfiguration: Missing Inbound Signature",
    "WebSphere Service Provider Misconfiguration: Missing Outbound Timestamp",
    "WebSphere Service Provider Misconfiguration: Outbound WS-Security Not Enabled",
    "WebSphere Service Requester Misconfiguration: Outbound WS-Security Not Enabled",
    "XML Entity Expansion Injection",
    "ClassLoader Manipulation: Struts 1",
    "Code Correctness: Byte Array to String Conversion",
    "Code Correctness: Call to System.gc()",
    "Code Correctness: clone() Invokes Overridable Function",
    "Cross-Site Scripting: Self",
    "Denial of Service: StringBuilder",
    "Dynamic Code Evaluation: Unsafe Deserialization",
    "EJB Bad Practices: Use of AWT/Swing",
    "HTML5: Overly Permissive CORS Policy",
    "Insecure Transport: Disabled App Transport Security",
    "J2EE Misconfiguration: Missing Authentication Method",
    "J2EE Misconfiguration: Missing Servlet Mapping",
    "Key Management: Empty Encryption Key",
    "Missing Check against Null",
    "Often Misused: Authentication",
    "Often Misused: File Upload",
    "Password Management: Hardcoded Password",
    "Path Manipulation",
    "Path Manipulation: Zip Entry Overwrite",
    "Poor Error Handling: Empty Catch Block",
    "Poor Error Handling: Throw Inside Finally",
    "Session Fixation",
    "Struts 2 Bad Practices: Dynamic Method Invocation",
    "Struts 2: Validation File Without Action",
    "Struts Misconfiguration: Missing Form Property Type",
    "Struts: Erroneous validate() Method",
    "Struts: Unused Action Form",
    "Struts: Validator Turned Off",
    "Trust Boundary Violation",
    "Unchecked Return Value",
    "Unreleased Resource: Sockets",
    "Unreleased Resource: Streams",
    "Unsafe Mobile Code: Inner Class",
    "Unsafe Reflection",
    "Weak Encryption",
    "Weak Encryption: Inadequate RSA Padding",
    "Weak XML Schema: Lax Processing",
    "Weak XML Schema: Unbounded Occurrences",
    "WebSphere Misconfiguration: Servlets Served By Class Name",
    "XPath Injection",
    "Access Control: Weak Security Constraint",
    "Access Specifier Manipulation",
    "AngularJS Misconfiguration: Strict Contextual Escaping Disabled",
    "Code Correctness: Incorrect Serializable Method Signature",
    "Code Correctness: Incorrect serialPersistentFields Modifier",
    "Code Correctness: null Argument to equals()",
    "Cookie Security: HTTPOnly not Set",
    "Cross-Site Scripting: DOM",
    "Dead Code: Unused Method",
    "Dynamic Code Evaluation: JNDI Reference Injection",
    "EJB Bad Practices: Use of Class Loader",
    "File Disclosure: Struts",
    "J2EE Bad Practices: Sockets",
    "J2EE Misconfiguration: Duplicate Servlet Mapping",
    "J2EE Misconfiguration: Excessive Servlet Mappings",
    "J2EE Misconfiguration: Incomplete Error Handling",
    "Null Dereference",
    "OGNL Expression Injection: Double Evaluation",
    "OGNL Expression Injection: Struts 2",
    "Open Redirect",
    "Password Management: Insecure Submission",
    "Privacy Violation: Autocomplete",
    "Privilege Management: Default Package Rights",
    "Privilege Management: Overly Broad Access Specifier",
    "Race Condition: Class Initialization Cycle",
    "Race Condition: Singleton Member Field",
    "Race Condition: Static Database Connection",
    "SQL Injection",
    "Struts: Plugin Framework Not In Use",
    "System Information Leak: Incomplete Servlet Error Handling",
    "WebSphere Service Provider Misconfiguration: Missing Inbound Timestamp",
    "WebSphere Service Provider Misconfiguration: Missing Outbound Signature",
    "WebSphere Service Requester Misconfiguration: Inbound WS-Security Not Enabled",
    "WebSphere Service Requester Misconfiguration: Missing Outbound Encryption",
    "ASP.NET Misconfiguration: Debug Information",
    "Code Correctness: Class Does Not Implement equals",
    "Code Correctness: Erroneous Null Comparison",
    "Code Correctness: Multiple Stream Commits",
    "Code Correctness: String Comparison of Float",
    "Cookie Security: Persistent Cookie",
    "Dangerous File Inclusion",
    "Dead Code: Empty Try Block",
    "Dead Code: Expression is Always true",
    "Dead Code: Unused Field",
    "Denial of Service",
    "Denial of Service: Format String",
    "Denial of Service: Regular Expression",
    "Formula Injection",
    "Hardcoded Domain in HTML",
    "Hidden Field",
    "Insecure SSL: Overly Broad Certificate Trust",
    "J2EE Misconfiguration: Missing Error Handling",
    "J2EE Misconfiguration: Missing Security Role",
    "JavaScript Hijacking: Vulnerable Framework",
    "LDAP Injection",
    "LDAP Manipulation",
    "Log Forging (debug)",
    "Missing Check for Null Parameter",
    "OGNL Expression Injection: Dynamic Method Invocation",
    "Password Management: Password in HTML Form",
    "Poor Error Handling: Overly Broad Catch",
    "Poor Error Handling: Return Inside Finally",
    "Poor Logging Practice: Multiple Loggers",
    "Poor Style: Value Never Read",
    "Privacy Violation",
    "Server-Side Request Forgery",
    "Struts 2: Unvalidated Action",
    "Struts: Form Field Without Validator",
    "Struts: Validator Without Form Field",
    "System Information Leak: Overly Broad SQL Logging",
    "Unreleased Resource: Database",
    "Unsafe Mobile Code: Unsafe Public Field",
    "Weak XML Schema: Type Any",
    "WebSphere Service Provider Misconfiguration: Inbound WS-Security Not Enabled",
    "WebSphere Service Provider Misconfiguration: Missing Outbound Encryption",
    "WebSphere Service Requester Misconfiguration: Missing Inbound Encryption",
    "WebSphere Service Requester Misconfiguration: Missing Inbound Timestamp",
    "WebSphere Service Requester Misconfiguration: Missing Outbound Timestamp",
    "Axis 2 Service Provider Misconfiguration: WS-Security Not Enabled",
    "Build Misconfiguration: External Maven Dependency Repository",
    "Code Correctness: Hidden Method",
    "Code Correctness: Invalid Call to Object.equals()",
    "Code Correctness: Non-Synchronized Method Overrides Synchronized Method",
    "Command Injection",
    "Cookie Security: Overly Broad Path",
    "Cross-Site Scripting: Poor Validation",
    "Cross-Site Scripting: Reflected",
    "Dynamic Code Evaluation: Script Injection",
    "Dynamic Code Evaluation: XMLDecoder Injection",
    "HTML5: MIME Sniffing",
    "HTML5: Overly Permissive Message Posting Policy",
    "HTTP Verb Tampering",
    "Insecure Transport: Mail Transmission",
    "J2EE Bad Practices: Leftover Debug Code",
    "J2EE Bad Practices: Threads",
    "J2EE Misconfiguration: Missing Data Transport Constraint",
    "JavaScript Hijacking",
    "JSON Injection",
    "Key Management: Hardcoded Encryption Key",
    "Mass Assignment: Sensitive Field Exposure",
    "Missing XML Validation",
    "Object Model Violation: Erroneous clone() Method",
    "Object Model Violation: Just one of equals() and hashCode() Defined",
    "Password Management",
    "Password Management: Null Password",
    "Password Management: Password in Comment",
    "Password Management: Password in Configuration File",
    "Poor Error Handling: Overly Broad Throws",
    "Poor Error Handling: Program Catches NullPointerException",
    "Poor Style: Non-final Public Static Field",
    "Privacy Violation: Heap Inspection",
    "Process Control",
    "Redundant Null Check",
    "Resource Injection",
    "Setting Manipulation",
    "Struts: Duplicate Validation Forms",
    "Struts: Form Does Not Extend Validation Class",
    "System Information Leak: External",
    "Unsafe JNI",
    "Weak Cryptographic Hash",
    "Weak Encryption: Insecure Initialization Vector",
    "WebSphere Service Provider Misconfiguration: Missing Inbound Encryption",
    "XML External Entity Injection",
    "XSLT Injection",
    "Access Control: Database",
    "Access Control: LDAP",
    "Code Correctness: Class Does Not Implement Cloneable",
    "Code Correctness: Comparison of Boxed Primitive Types",
    "Code Correctness: Erroneous finalize() Method",
    "Code Correctness: Non-Static Inner Class Implements Serializable",
    "Code Correctness: readObject() Invokes Overridable Function",
    "Code Correctness: toString on Array",
    "Cookie Security: Cookie not Sent Over SSL",
    "Dead Code: Expression is Always false",
    "Dynamic Code Evaluation: Code Injection",
    "EJB Bad Practices: Use of java.io",
    "EJB Bad Practices: Use of Sockets",
    "EJB Bad Practices: Use of Synchronization Primitives",
    "Header Manipulation: Cookies",
    "Header Manipulation: SMTP",
    "Insecure Randomness",
    "Insecure Randomness: Hardcoded Seed",
    "Insecure Transport",
    "J2EE Misconfiguration: Insecure Transport",
    "J2EE Misconfiguration: Missing Filter Definition",
    "Often Misused: Boolean.getBoolean()",
    "Poor Style: Confusing Naming",
    "Poor Style: Identifier Contains Dollar Symbol ($)",
    "Poor Style: Redundant Initialization",
    "Portability Flaw: File Separator",
    "Race Condition: Format Flaw",
    "Spring Security Misconfiguration: Incorrect Request Matcher Type",
    "Struts Misconfiguration: Duplicate Form Bean",
    "Struts Misconfiguration: Invalid Path",
    "Struts: Unused Validation Form",
    "System Information Leak",
    "System Information Leak: HTML Comment in JSP",
    "System Information Leak: Internal",
    "Unreleased Resource: Files",
    "WCF Misconfiguration: Throttling Not Enabled",
    "Weak Encryption: Insufficient Key Size",
    "Cookie Security: HTTPOnly not Set on Application Cookie",
    "Code Correctness: Erroneous String Compare",
    "Poor Error Handling: Unhandled SSL Exception",
    "Weak SecurityManager Check: Overridable Method",
    "XML Injection",
    "Insecure Randomness: Weak Entropy Source",
    "Struts 2: Action Field Without Validator",
    "Session Puzzling: Spring",
    "Code Correctness: Call to Thread.run()",
    "Dynamic Code Evaluation: Unsafe XStream Deserialization",
    "Mass Assignment: Insecure Binder Configuration",
    "Code Correctness: Call to notify()",
    "Cross-Session Contamination",
    "Database Bad Practices: Use of Restricted Accounts",
    "Fortify Internal",
    "Weak Cryptographic Hash: Hardcoded PBE Salt",
    "Code Correctness: Class Does Not Implement Equivalence Method",
    "WebSphere Misconfiguration: Missing Nonce",
    "ASP.NET Misconfiguration: Missing Error Handling",
    "Cookie Security: Missing SameSite Attribute",
    "Dynamic Code Evaluation: Insecure Transport",
    "Insecure SSL: Server Identity Verification Disabled",
    "WebSphere Service Requester Misconfiguration: Unsigned Outbound Timestamp",
    "Code Correctness: null Argument To Equivalence Method",
    "Encoding Confusion: BiDi Control Characters",
    "HTML5: Cross-Site Scripting Protection",
    "Insecure Transport: Weak SSL Protocol",
    "Credential Management: Hardcoded API Credentials",
    "Insecure Transport: External Link",
    "Web Server Misconfiguration: Insecure Content-Type Setting",
    "Web Server Misconfiguration: Server Error Message",
    "WebSphere Service Requester Misconfiguration: Missing Outbound Signature",
    "Often Misused: Weak SSL Certificate",
    "Insecure Deployment: Known Technology Fingerprint",
    "Insecure Transport: Weak SSL Cipher",
    "Path Manipulation: Special Characters",
    "Cache Management: Insecure Policy",
    "Insecure Transport: Missing Perfect Forward Secrecy",
    "HLI: Detected Libraries : Dojo v1.9.7_IBM_CVE-2018-15494_CVE-2020-5258_CVE-2021-23450 (2dfbbaf)",
    "Insecure Transport: HSTS not Set",
    "Poor Style: Empty Synchronized Block",
    "WebSphere Service Requester Misconfiguration: Missing Inbound Signature",
    "Kubernetes Bad Practices: Missing Security Context",
    "Kubernetes Bad Practices: Service Account Token Automounted",
    "OpenAPI Misconfiguration: Missing Operation Security Requirement",
    "SQL Injection: Persistence",
    "OpenAPI Misconfiguration: Missing Global Security Requirement",
    "React Bad Practices: Dangerously Set InnerHTML",
    "Unauthenticated Service: Redis",
    "OpenAPI Misconfiguration: Missing Security Schemes",
    "Dockerfile Misconfiguration: Default User Privilege",
    "Spring Boot Misconfiguration: DevTools Enabled",
    "System Information Leak: Spring Boot Actuators Enabled",
    "Cross-Site Scripting: Content Sniffing",
    "Dockerfile Misconfiguration: Sensitive Host Directory",
    "OpenAPI Misconfiguration: Missing Error Handling",
    "Password Management: Shared Password Database",
    "OpenAPI Misconfiguration: Insecure Transport",
    "Code Correctness: Comparison with NaN",
    "Insecure SSL: Inadequate Certificate Verification",
    "Insecure Storage: Android Backup Storage",
    "Privilege Management: Android Calendar",
    "Privilege Management: Android Camera",
    "Privilege Management: Android Data Storage",
    "Privilege Management: Unnecessary Permission",
    "Weak Cryptographic Hash: User-Controlled Algorithm",
    "Weak Cryptographic Signature",
    "Access Control: Anonymous LDAP Bind",
    "Android Bad Practices: Missing Network Security Configuration",
    "Code Correctness: Misleading Method Signature",
    "Privacy Violation: iOS Property List",
    "WCF Misconfiguration: Weak Token",
    "Android Bad Practices: Missing Component Permission",
    "Android Bad Practices: System Permission Defined",
    "Android Misconfiguration: Debug Information",
    "ASP.NET Misconfiguration: Request Validation Disabled",
    "Insecure SSL: Android Customized Implementation",
    "Privilege Management: Android Location",
    "WCF Misconfiguration: Transport Security Enabled",
    "Weak Cryptographic Hash: User-Controlled PBE Salt",
    "Weak Encryption: Missing Required Step",
    "ASP.NET Misconfiguration: Excessive Session Timeout",
    "Insecure Transport: Database",
    "Missing SecurityManager Check: Cloneable",
    "Privilege Management: Android Microphone",
    "WCF Misconfiguration: Insecure Transport",
    "Cookie Security: Session Cookie not Sent Over SSL",
    "Missing SecurityManager Check: Serializable",
    "Privilege Management: Android Contacts",
    "WCF Misconfiguration: Anonymous Transport Client",
    "WCF Misconfiguration: Debug Information",
    "WCF Misconfiguration: Security Not Enabled",
    "Android Bad Practices: Missing Google Play Services Updated Security Provider",
    "Android Bad Practices: Use of Internal APIs",
    "LDAP Entry Poisoning",
    "Privilege Management: Android Telephony",
    "Privilege Management: Missing API Permission",
    "Privilege Management: Dangerous Intent Permission",
    "Insecure Storage: Android External Storage",
    "Unreleased Resource: Android SQLite Database",
    "HTML5: Easy-to-Guess Database Name",
    "Privilege Management: Android Call Log",
    "Privilege Management: Android Messaging",
    "Privilege Management: Missing Intent Permission",
    "Android Bad Practices: Unnecessary Component Exposure",
    "Android Class Loading Hijacking",
    "Insecure SSL: Android Hostname Verification Disabled",
    "Android Bad Practices: Missing exported Flag or Component Permission",
    "Unreleased Resource: Synchronization",
    "OpenAPI Misconfiguration: Weak Authentication",
    "Struts 2: Validator Without Action Field",
    "HTTP Parameter Pollution",
    "Password Management: Weak Cryptography",
    "Struts 2: Undeclared Validator",
    "Struts 2: Duplicate Validation Files",
    "Template Injection",
    "Poor Style: Explicit Call to finalize()",
    "Axis 2 Service Provider Misconfiguration: Outbound WS-Security Not Enabled"]

BSV_DATA = [
    "Apache Log4j 1.x Multiple Vulnerabilities",
    "Apache Log4j SEoL (<= 1.x)",
    "Apache Struts SEoL (1.0.x <= x <= 1.3.10.x)",
    "Apache Struts 2.0.0 <=> 2.3.37(EOL) / 2.5.0 <=> 2.5.33 / 6.0.0 <=> 6.3.0.2 Remote Code Execution (S2-067)",
    "Apache Struts SEoL (2.3.0.x <= x <= 2.3.37.x)",
    "Apache CXF < 3.6.8 / 4.x < 4.0.9 / 4.1.x < 4.1.3 RCE (CVE-2025-48913)",
    "Oracle Java JRE Unsupported Version Detection (Unix)",
    "Spring Framework < 4.3.16 / 5.0.x < 5.0.5 Remote Code Execution with spring-messaging (CVE-2018-1270)",
    "Apache CXF < 3.5.9, 3.6.x < 3.6.4, 4.0.x < 4.0.5 Multiple Vulnerabilities",
    "Apache CXF < 3.5.8, 3.6.x < 3.6.3, 4.0.x < 4.0.4 SSRF",
    "Spring Security < 5.5.7 / 5.6.x < 5.6.4 Authorization Bypass",
    "Apache Commons Text 1.5.x < 1.10.0 Remote Code Execution (CVE-2022-42889)",
    "Apache Log4j 1.2 JMSAppender Remote Code Execution (CVE-2021-4104)",
    "Spring Framework 5.3.x < 5.3.45 / 6.1.x < 6.1.23 / 6.2.x < 6.2.11 Annotation Detection Vulnerability (CVE-2025-41249)",
    "Spring Framework < 5.3.32 / 6.0.x < 6.0.17 / 6.1.x < 6.1.4 Open Redirect (CVE-2024-22243)",
    "Spring Framework < 5.3.33 / 6.0.x < 6.0.18 / 6.1.x < 6.1.5 Open Redirect (CVE-2024-22259)",
    "Spring Framework < 5.3.40 / 6.0.x < 6.0.24 / 6.1.x < 6.1.13 Path Traversal (CVE-2024-38816)",
    "Apache Struts < 2.5.31 / 6.1.2.1 Denial of Service (S2-064)",
    "Spring Security 5.7 < 5.7.16 / 5.8 < 5.8.18 / 6.0 < 6.0.16 / 6.1 < 6.1.14 / 6.2 < 6.2.10 / 6.3 < 6.3.8 / 6.4 < 6.4.4 Authentication Bypass (CVE-2025-22228)",
    "Insecure Windows Service Permissions",
    "IBM Java 8.0 < 8.0.8.50 Multiple Vulnerabilities",
    "Apache Struts 2.0.0 < 6.1.2.1 Denial of Service (S2-063)",
    "Apache POI < 5.4.0 Improper Input Validation",
    "Spring Framework 5.3.x < 5.3.44 / 6.1.x < 6.1.22 / 6.2.x < 6.2.10 Path Traversal (CVE-2025-41242)",
    "Spring Framework < 5.3.39 / 6.0.x < 6.0.23 / 6.1.x < 6.1.12 HTTP Request DoS (CVE-2024-38809)",
    "Spring Framework < 5.3.41 / 6.0.x < 6.0.25 / 6.1.x < 6.1.14 Multiple Vulnerabilities",
    "Apache Log4j 2.x < 2.17.0 DoS",
    "Spring Framework 5.3.x < 5.3.42 DoS (CVE-2024-38828)",
    "Spring Framework < 5.3.39 Spring Expression DoS (CVE-2024-38808)",
    "Apache Log4j 2.0 < 2.3.2 / 2.4 < 2.12.4 / 2.13 < 2.17.1 RCE",
    "Spring_framework 5.3.x < 5.3.43 / 6.0.x < 6.0.28 / 6.1.x < 6.1.20 / 6.2.x < 6.2.7 (CVE-2025-22233)"
]

SDU_DATA = [
    "jQuery 1.4.2 < 1.6.2 Cross-Site Scripting",
    "jQuery 1.4.0 < 1.12.0 Cross-Site Scripting",
    "jQuery < 1.6.3 Cross-Site Scripting",
    "Missing HTTP Strict Transport Security Policy",
    "jQuery 1.2.0 < 3.5.0 Cross-Site Scripting",
    "Host Header Injection",
    "Insecure Redirect Chain",
    "ASP.NET ViewState Not Encrypted",
    "jQuery 1.12.4 < 3.0.0 Cross-Site Scripting",
    "jQuery < 3.4.0 Prototype Pollution",
    "SSL/TLS Forward Secrecy Cipher Suites Not Supported",
    "jQuery UI < 1.12.0 Cross-Site Scripting",
    "jQuery UI < 1.13.2 Cross-Site Scripting",
    "jQuery UI < 1.13.0 Multiple Vulnerabilities",
    "Password Submitted using get Method",
    "jQuery 1.7.1 < 1.9.0 Cross-Site Scripting",
    "jQuery < 1.9.0 Cross-Site Scripting",
    "HTTP to HTTPS Redirect Not Enabled",
    "Microsoft IIS Tilde Character Short File/Folder Name Disclosure",
    "Cookie Without HttpOnly Flag Detected",
    "Cookie Without SameSite Flag Detected",
    "Cookie Without Secure Flag Detected",
    "Missing Content Security Policy",
    "Login Form Cross-Site Request Forgery",
    "Missing 'Cache-Control' Header",
    "Permissive Content Security Policy Detected",
    "Missing 'X-Content-Type-Options' Header",
    "Missing 'X-Frame-Options' Header",
    "Password Field With Auto-Complete",
    "SSL/TLS Weak Cipher Suites Supported",
    "HTTP Header Information Disclosure",
    "Content Security Policy Missing 'Report-To'"
]